<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<OutputType>Library</OutputType>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="OpenTK.GLWpfControl" Version="4.3.4" />
		<PackageReference Include="Poly2Tri" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OpenCAD\OpenCAD.csproj" />
		<ProjectReference Include="..\OpenCAD.TextRendering\OpenCAD.TextRendering.csproj" />
	</ItemGroup>
</Project>

