<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\Editing\TrimCommand.cs" />
    <Compile Remove="Controls\Viewport\ViewportViewModelForTrim.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\arc.png" />
    <None Remove="Resources\Icons\arc_3pt.png" />
    <None Remove="Resources\Icons\arc_cont.png" />
    <None Remove="Resources\Icons\arc_sca.png" />
    <None Remove="Resources\Icons\arc_sce.png" />
    <None Remove="Resources\Icons\arc_sed.png" />
    <None Remove="Resources\Icons\arc_sel.png" />
    <None Remove="Resources\Icons\arc_ser.png" />
    <None Remove="Resources\Icons\circle.png" />
    <None Remove="Resources\Icons\circle_2pt.png" />
    <None Remove="Resources\Icons\circle_3pt.png" />
    <None Remove="Resources\Icons\circle_cd.png" />
    <None Remove="Resources\Icons\circle_cr.png" />
    <None Remove="Resources\Icons\copy.png" />
    <None Remove="Resources\Icons\dimesion.png" />
    <None Remove="Resources\Icons\dim_linear.png" />
    <None Remove="Resources\Icons\erase.png" />
    <None Remove="Resources\Icons\fillet.png" />
    <None Remove="Resources\Icons\Line.png" />
    <None Remove="Resources\Icons\move.png" />
    <None Remove="Resources\Icons\offset.png" />
    <None Remove="Resources\Icons\polyline.png" />
    <None Remove="Resources\Icons\rotate.png" />
    <None Remove="Resources\Icons\scale.png" />
    <None Remove="Resources\Icons\text.png" />
    <None Remove="Resources\menus.json" />
    <None Remove="Resources\OpenCAD.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Themes\DarkTheme.xaml" />
    <Page Remove="Themes\LightTheme.xaml" />
    <Page Remove="Themes\WindowChrome.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonDock.Themes.VS2013" Version="2.0.0.5" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
    <PackageReference Include="OpenTK.Windowing.Common" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphicsEngine\GraphicsEngine.csproj" />
    <ProjectReference Include="..\OpenCAD.TextRendering\OpenCAD.TextRendering.csproj" />
    <ProjectReference Include="..\OpenCAD\OpenCAD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\arc.png" />
    <Resource Include="Resources\Icons\arc_3pt.png" />
    <Resource Include="Resources\Icons\arc_cont.png" />
    <Resource Include="Resources\Icons\arc_sca.png" />
    <Resource Include="Resources\Icons\arc_sce.png" />
    <Resource Include="Resources\Icons\arc_sed.png" />
    <Resource Include="Resources\Icons\arc_sel.png" />
    <Resource Include="Resources\Icons\arc_ser.png" />
    <Resource Include="Resources\Icons\circle.png" />
    <Resource Include="Resources\Icons\circle_2pt.png" />
    <Resource Include="Resources\Icons\circle_3pt.png" />
    <Resource Include="Resources\Icons\circle_cd.png" />
    <Resource Include="Resources\Icons\circle_cr.png" />
    <Resource Include="Resources\Icons\copy.png" />
    <Resource Include="Resources\Icons\dimesion.png" />
    <Resource Include="Resources\Icons\dim_linear.png" />
    <Resource Include="Resources\Icons\erase.png" />
    <Resource Include="Resources\Icons\fillet.png" />
    <Resource Include="Resources\Icons\Line.png" />
    <Resource Include="Resources\Icons\move.png" />
    <Resource Include="Resources\Icons\offset.png" />
    <Resource Include="Resources\Icons\polyline.png" />
    <Resource Include="Resources\Icons\rotate.png" />
    <Resource Include="Resources\Icons\scale.png" />
    <Resource Include="Resources\Icons\text.png" />
    <Resource Include="Resources\menus.json" />
    <Resource Include="Resources\OpenCAD.jpg" />
    <Resource Include="Themes\DarkTheme.xaml" />
    <Resource Include="Themes\LightTheme.xaml" />
    <Resource Include="Themes\WindowChrome.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Support\OpenCAD.lin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>

</Project>
